import time, os, colorama, open
from colorama import *

def clear(x):
    time.sleep(x)
    os.system('cls')

clear(1)
print(Style.BRIGHT + Fore.GREEN + '\nC')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCr')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCre')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCrea')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreat')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate b')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by R')
clear(0.30)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by Ru')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by Rus')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by Rusm')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by Rusma')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by Rusmay')
clear(0.7)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by Rusma')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by Rusm')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by Rus')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by Ru')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by R')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate by')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate b')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreate')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCreat')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCrea')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCre')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nCr')
clear(0.25)
print(Style.BRIGHT + Fore.GREEN + '\nC')
clear(0.25)
time.sleep(1)
print(Style.BRIGHT + Fore.GREEN + '|-------------------------|')
time.sleep(0.1)
print()
time.sleep(0.1)
print(Style.BRIGHT + Fore.GREEN + '    Create by Rusmay')
time.sleep(0.1)
print()
time.sleep(0.1)
print(Style.BRIGHT + Fore.GREEN + '|-------------------------|')
time.sleep(0.1)
print()
time.sleep(0.1)
log = input(Style.BRIGHT + Fore.GREEN + 'Login: ')
pas = int(input(Style.BRIGHT + Fore.GREEN + 'Password: '))
time.sleep(0.3)
print()
time.sleep(0.3)
print(Style.BRIGHT + Fore.GREEN + '|-------------------------|')
time.sleep(0.3)
print()
clear(0.1)

open.openn()